version: "3.8"

services:
  console:
    container_name: console
    build: ./mangato-console
    ports:
      - 3000:3000
  api:
    container_name: api
    build: ./mangato-api
    environment:
      # - MANGATO_DETECT_API=http://192.168.158.4:5000/detect
      - MANGATO_DETECT_API=${MANGATO_DETECT_API}
    ports:
      - 3001:3001
  detect:
    container_name: detect
    build: ./detect-api
    ports:
      - 5000:5000
  # nginx:
  #   container_name: nginx
  #   build: ./nginx
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
